export const Data = {
  Clothing: [
    "All Clothing",
    "Beachwear",
    "Coats",
    "Dresses",
    "Hosiery",
    "Jackets",
    "Jeans",
    "Jumpsuits",
    "Knitwear",
    "Lingerie",
    "Nightwear",
    "+ More",
  ],
  Shoes: [
    "All Shoes",
    "Boots",
    "Flats",
    "Heels",
    "Sneakers",
    "New Arrivals in Shoes",
    "Back in Stock Shoes",
    "Shoes on Sale",
  ],
  Accessories: [
    "All Accessories",
    "Belts",
    "Cases",
    "Face masks",
    "Gloves",
    "Hair",
    "Hats",
    "Scarves",
    "Sunglasses",
    "Umbrellas",
    "+ More",
  ],
  Bags: [
    "All Bags",
    "Bag packs",
    "Bag accessories",
    "Beach and straw bags",
    "Belt bags",
    "Briefcases and work bags",
    "Bucket bags",
    "Clutches",
    "Crossbody bags",
    "Holdalls and weekend bags",
    "+ More",
  ],
  Jewelry: [
    "All Jewelry",
    "Bracelets",
    "Brooches",
    "Earrings",
    "Necklaces",
    "Rings",
    "New Arrivals in Jewelry",
    "Back in Stock Jewelry",
    "Jewelry on Sale",
  ],
  Brands: [
    "Balenciaga",
    "Bottega Veneta",
    "Chloé",
    "Ganni",
    "Gucci",
    "H&M",
    "Isabel Marant",
    "& Other Stories",
    "Prada",
    "Reformation",
  ],
};
